version: '2'
services:
  front:
    build: ./front
    command: bash -c "npm install --save && npm run build-js && npm run dev"
    volumes:
      - ./front/jwt:/root/jwt
  backend:
    build: ./backend
    command: bash -c "bundle install && rails db:migrate && rails s -e development"
    volumes:
      - ./backend/api:/root/api
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - "front"
      - "backend"
