default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: friend_books
  password: password
  host: db

development:
  <<: *default
  database: friend_books_development

test:
  <<: *default
  database: friend_books_test

production:
  <<: *default
  database: friend_books_production
  username: friend_books
  password: <%= ENV['FRIEND_BOOKS_DATABASE_PASSWORD'] %>
